scoop install 7zip
scoop install sharex
scoop install autohotkey
scoop install git
scoop install oh-my-posh
scoop install neovim
scoop install wezterm
scoop install ffmpeg
scoop install python
scoop install python3
scoop install nodejs
scoop install ffmpeg
scoop install losslesscut
scoop install obs-studio
scoop install fastfetch
scoop install spotify     
scoop install discord
scoop install rustup
scoop install figma        
scoop install steam       
scoop install aria2
scoop install cascadia-code
scoop install fzf
scoop install jid
scoop install jq
scoop install k9s
scoop install kubectl
scoop install lazydocker
scoop install lazygit
scoop install oh-my-posh
scoop install pwsh
scoop install yazi
scoop install zoxide
